### ISSUE TITLE
Update 2: Initial Network & Tests

### ISSUE THREAD

**Issue by gavinmcdermott** [gavinmcdermott/js-libp2p-pstn#2]
Update for @diasdavid:

### Status Update
- **Initial Network:** Initial implementation is now running reliably in the latest push. I've spun up to 6K connected nodes at once just using the fact that Promises are tail optimized (nothing multi-core, etc. yet).  (`npm start` will boot up a 2k node network)
- **Tests:** Added some [initial tests](https://github.com/gavinmcdermott/pubsub_testnet/blob/master/test/network.js) - right now for a 1K node network size, but you can dial up in as needed  (`npm test` will run tests against a 100 node network - tweak as needed)

#### Note
- I [shrank the keyspace](https://github.com/gavinmcdermott/pubsub_testnet/blob/master/src/network.js#L30) for speed. Let me know if this is a major issue at this stage

### Questions

1. I'm still a bit hazy with regards to:
  * where/how I can best (eventually) add options to allow people to configure/implement a specified peer discover/routing mechanism, which also ties in with, and
  * how best to bootstrap the network nodes

1. With the above in mind, specifically it comes to mind in [this function](https://github.com/gavinmcdermott/pubsub_testnet/blob/master/src/network.js#L83-L130) is where all of the initial bootstrapping is done. It is based on my limited (growing) understanding, and I'd like to get your feedback on how I might implement some smarter/more configurable bootstrapping optionality based on the two bullets above. I realize it doesn't all need to be in the lib from the start, but I'd like to make sure the initial implementation is solid—this'll also help my understanding. 

2. I haven't looked into it yet, but next up is adding some options for nodes dropping / faking latency issues, and the like. I figured to just ask if, off the top of mind, you are aware of any areas in the libp2p codebase / properties available on nodes that implement it that might be useful for me...thought I'd ask :)

3. If possible, even a brief code review on the latest `master` just to make sure it's progressing in line with what the commitments were would be really appreciated

### Next Up

Based on the plan you saw from last week, here's where I'm at and what's coming up later this week. I'll also probably reach out to some people for guidance/help with the container-strategy over the weekend / early next week.

- [x] Get the basics working on a local machine 
- [x]  Ability to spin up a few thousand nodes quickly
- [x]  Plus basic tests

**Comment by gavinmcdermott** [comment]
Also: @hermanjunge, this might be reaching a good time to chat with regards to docker infrastructure for the testnet. Love to connect if you're around some time in the next few days. Feel free to let me know!

**Comment by hermanjunge** [comment]
@gavinmcdermott send me your email via `gitter` or `twitter`. I am @hermanjunge there.

**Comment by gavinmcdermott** [comment]
Pinging @diasdavid (in case this was lost in the email landslide)

**Comment by diasdavid** [comment]
Apologies for the delay in getting back to you @gavinmcdermott, I was travelling and acquired a bit of backlog. Jumping right into feedback and answering your questions :)

> 6K connected nodes at once just using the fact that Promises are tail optimized

What was the memory usage? What is the hardware you are using for these tests, I'm curious :)

> I shrank the keyspace for speed. Let me know if this is a major issue at this stage

It is ok if we don't use `secio` (the crypto channel), which is ok for pubsub testing. I understand how generating RSA in pure JS costs a lot of time. What we can do is just pre-image 10K keypairs and seed them out, because that is really the only CPU intensive task.

> I'm still a bit hazy with regards to:
  where/how I can best (eventually) add options to allow people to configure/implement a specified peer discover/routing mechanism, which also ties in with, and how best to bootstrap the network nodes

There are several ways to do this, but a time saver can be to reuse @whyrusleepings IPTB (InterPlanetary TestBed) module https://github.com/whyrusleeping/iptb, it basically can spawn nodes (go-ipfs nodes, right now) as separate processes or inside Docker containers.

This way, we can just start having IPTB daemons listening in different machines and have the IPTB cli to spawn nodes on those machines ( this is going to be awesome 💯 )

A good example, although rather old infra, is https://www.planet-lab.org/, it is the traditional testbed for p2p apps. A 'researcher' is able to request 'slices' (time from machines) to run programs. They provide a tool for deploying these scripts (named `codeploy`). It is not the most shiny thing for whom is used to modern microserviced architectures, but the model is there, machines are available, researchers/devs are able to 'request' a number of virtual instances, and then a tool helps setting and orchestrating all of that.

I've some more thoughts on this, specially because it will become super useful for the P2P Web era to be able to spawn browser runtimes across the world and test latencies and resilience for WebRTC packet switched networks. We need, adding to the deployment and running of this processes, be able to infer what happen (probs and monitoring) so that we can assessed if our routing logic is behaving as expected. 

The best is to start with "let's be able to spawn nodes anywhere" and then go to how to instruct them.

With regards to your other question "How to best bootstrat", an IPFS config file has an array of bootstrap nodes for the node to 'rail into the network'. I made this for a older version of libp2p https://github.com/libp2p/js-libp2p-railing, needs to be updated to work with latest libp2p-swarm.

> I haven't looked into it yet, but next up is adding some options for nodes dropping / faking latency issues, and the like. I figured to just ask if, off the top of mind, you are aware of any areas in the libp2p codebase / properties available on nodes that implement it that might be useful for me...thought I'd ask :)

@whyrusleeping has done this for go-ipfs tests with Docker, he will be able to give you a good direction on how to achieve this (AFAIK it requires a patch to Docker itself).

> If possible, even a brief code review on the latest master just to make sure it's progressing in line with what the commitments were would be really appreciated

On it :)

**Comment by diasdavid** [comment]
> https://github.com/gavinmcdermott/pubsub_testnet/blob/master/src/network.js#L3-L4

go-ipfs also suffers from this, although it now readjusts the limits automatically for the user.

Overall, the code looks good for what is its goal. Right now every node connects to every other node, it would be interesting to be able to create some topologies. It might be hard to create a generic function that understand every possible topology, but having some recipes such as:

- Full mesh - what you have right now
- Circular - Each node connects to the next node and the last node connects to the first
- Spanning Tree with factor N
- Clusters of N nodes - Each N nodes are fully connected and then link to the other clusters by one node

**Comment by gavinmcdermott** [comment]
No need to apologize for the delay! Rather, I owe you a thank you! The feedback is sincerely appreciated.

**Comment by gavinmcdermott** [comment]
Hey @diasdavid - Thanks again for the input, now to your questions:
> What was the memory usage? What is the hardware you are using for these tests, I'm curious :)

3.1GHz processor / 16GB memory. And the current implementation can seriously be improved, how I'm allocating and passing objects, etc...

> What we can do is just pre-image 10K keypairs and seed them out, because that is really the only CPU intensive task

I'll do this at some point; just not likely in the next week ;)

> The best is to start with "let's be able to spawn nodes anywhere" and then go to how to instruct them.

I'm in this mode right now, talking with @hermanjunge about clustering

> Right now every node connects to every other node, it would be interesting to be able to create some topologies

I'm on it this weekend. Along with a few other items before getting into working with containers.
